# -*- coding: utf-8 -*-
"""
Created on Mon Apr  3 16:53:09 2023

@author: Gavin
"""

LUNA16_RAW_DATA_DIR = 'B:/Datasets/LUNA16-DICOM'
LUNA16_PREPROCESSED_DATA_DIR = 'B:/Datasets/LUNA16-DICOM/preprocessed'

NSCLC_RAW_DATA_DIR = 'B:/Datasets/NSCLC'
NSCLC_PREPROCESSED_DATA_DIR = 'B:/Datasets/LUNA16-DICOM/preprocessed'

OUT_DIR = 'out'

IMG_SIZE = 512

CT_MIN = -1024
CT_MAX = 3072

TRAIN_FRACTION = 0.7

LUNA16_NUM_SUBSETS = 4
NSCLC_NUM_SUBSETS = 4

LUNA16_TRACHEA_FRACTION = 0.6 / 100
NSCLC_TRACHEA_FRACTION = 0.3 / 100