seed: 0
dataset: LUNA16
dataset_type: nodules
model: UNet
device: cuda
zoom_transform: false
optimizer_arguments:
  epochs: 100
  lr: 0.01
  cum_batch_size: 20
  valid_freq: 1
loading_arguments:
  num_workers: 10
dataloader_arguments:
  batch_size: 8
  train_idx: 0
