seed: 0
dataset: NSCLC
dataset_type: nodules
model: UNet
device: cuda
optimizer_arguments:
  epochs: 100
  lr: 0.001
  cum_batch_size: 20
  valid_freq: 10
loading_arguments:
  num_workers: 10
  zoom_transform: false
dataloader_arguments:
  batch_size: 8
  train_idx: 0
