seed: 0
dataset: LUNA16
dataset_type: nodules
model: UNet
device: cuda
zoom_transform: false
train: true
test: false
cross_valid: true
model_arguments:
  channels: 16
  img_channels: 2
optimizer_arguments:
  epochs: 500
  lr: 0.001
  cum_batch_size: 20
  valid_freq: 1
  wbce_weight: 1
  dice_weight: 100
loading_arguments:
  num_workers: 8
  mask_lungs: true
dataloader_arguments:
  batch_size: 8
  train_idx: 0
